apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    env: dev
spec:
  containers:
  - name: httpd
    image: httpd
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
